### ISSUE TITLE
PlayerDurationObserver not publishing changes

### ISSUE THREAD

**Issue by husninazer** [ChrisMash/AVPlayer-SwiftUI#1]
i used the code for my project but couldn't get the PlayerDurationObserver working whenever an item is changed tin the AVplayer. i tried changing audio items both in the View init function and onAppear function .

As a result currentDuration is always 0.

**Comment by ChrisMash** [comment]
Hi, presumably the sample I provided works for you, it just stops working when you try and put it into your own project and maybe move things around a bit? If you can share your code with me here I'm happy to take a look and see if I can spot it?

**Comment by husninazer** [comment]
Hi Chris,
Yes that was the issue, there where 2 instances of AVPlayer and now its working. Also the slider doesnt work as intended on user inputs, like slide freely to a point. Do you have that issue or only my problem?

**Comment by ChrisMash** [comment]
That wasn’t an issue with my code so I imagine it’s something specific to yours. Maybe the wrong value is being bound to the slider or something else is overriding it, such as the player’s time updating?
