### ISSUE TITLE
How to change the Video played

### ISSUE THREAD

**Issue by wowo4k** [ChrisMash/AVPlayer-SwiftUI#3]
very helpful code and is exactly doing what I was looking for. The only thing where I struggle is how to change the video to be played. Did you have any thoughts on that ?

**Comment by ChrisMash** [comment]
Hi Armin, if you look at `AudioView.swift` it shows how you might go about changing the item on the player. It might be a good idea to have the player passed into the view rather than created by it so that you can update the player item outside the view.

**Comment by wowo4k** [comment]
Hi Chris, thanks for the proposal. Didn't look at AudioView.swift in detail as I was focusing on Video. Will take a closer look there or follow to 2nd proposed track creating the player before and then passing it to the view. This path I already started to work on. 

Many Thanks Armin

**Comment by ChrisMash** [comment]
I'm assuming you've been getting on ok with my suggestion so I'll close this issue to keep things nice and tidy 😁 feel free to add any followup questions if you struggle though!
